name: "nba"
version: "1.0.0"
config-version: 2

profile: "nba"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nba: 
    1_sources:
      +schema: staging
      +materialized: view
    2_transform:
      +schema: transform
      +materialized: table
    3_marts:
      +schema: marts
      +materialized: table

seeds:
  nba: 
    schema: transform

